#!/bin/bash -el

function so_dependencies() {
    export DEBIAN_FRONTEND=noninteractive
    echo '------------------'
    if [ -f ${CURRENT_DIR}/requirements.apt ]; then
        set +e
        sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y --force-yes
        status=$?
        set -e
        if [ ${status} != 0 ]; then
            sudo apt-get update
            sudo -E apt-get install $(cat ${CURRENT_DIR}/requirements.apt) -y --force-yes
        else
            echo '1'
            cat $(CURRENT_DIR)/requirements.apt
        fi
    else
        echo '2'
        cat $(CURRENT_DIR)/requirements.apt
    fi 
}
