#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/base/deploy

source ${SOURCE_DIR}/config

if [! -d $HOME/.pip]; then
    mkdir $HOME/.pip
fi

cat > $HOME/.pip/pip.conf << "EOF"
[global]
index-url = http://pypi.iguokr.com/guokr/dev/+simple
[install]
use-mirrors = true
mirrors = http://pypi.iguokr.com/guokr/dev/+simple
EOF

cat > $HOME/.pydistutils.cfg << "EOF"
[easy_install]
index_url = http://pypi.iguokr.com/guokr/dev/+simple
EOF

if [ -f ${CURRENT_DIR}/requirements.txt ]; then
    cat $HOME/.pip/pip.conf
    cat $HOME/.pydistutils.cfg
    echo '-------------------------------------------'
	sudo pip install -r ${CURRENT_DIR}/requirements.txt
elif [ -f ${CURRENT_DIR}/setup.py ]; then
	sudo pip install ${CURRENT_DIR}/
fi

/home/application/.venv/bin/python ${SOURCE_DIR}/hooks.py
