#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# do not remove, circus is needed to manage application processes
# and its environment variables
apt-get update
apt-get install python-virtualenv curl git openssh-server python-pip libzmq-dev g++ python-dev wget libyaml-dev -y
virtualenv ${VENV_DIR}
${VENV_DIR}/bin/pip install circus==0.11.1 tsuru-circus tsuru-unit-agent
pip install tsuru-unit-agent

sed -ri 's/^session\s+required\s+pam_loginuid.so$/session optional pam_loginuid.so/' /etc/pam.d/sshd
mkdir /var/run/sshd
echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile

mkdir -p /etc/circus
cp ${SOURCE_DIR}/utils/circus.ini /etc/circus/circus.ini

wget http://nodejs.org/dist/v0.10.25/node-v0.10.25.tar.gz
tar xvf node-v0.10.25.tar.gz
cd node-v0.10.25 && ./configure && make && sudo make install
echo '-----*-------'
wget http://npmjs.org/install.sh && sudo bash install.sh
npm config set registry https://registry.npmjs.org/
npm config set strict-ssl false
