#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# do not remove, circus is needed to manage application processes
# and its environment variables
cat > /etc/apt/sources.list << "EOF"
deb http://mirrors.sohu.com/debian wheezy main non-free contrib
deb-src http://mirrors.sohu.com/debian wheezy main non-free contrib

deb http://security.debian.org/ wheezy/updates main contrib non-free
deb-src http://security.debian.org/ wheezy/updates main contrib non-free
EOF
apt-get update
apt-get install python-virtualenv curl git openssh-server python-pip libzmq-dev g++ python-dev wget libyaml-dev -y
virtualenv ${VENV_DIR}
mkdir ${VENV_DIR}/.pip
cat > ${VENV_DIR}/.pip/pip.conf << "EOF"
[global]
index-url = http://pypi.iguokr.com/guokr/dev/+simple
[install]
use-mirrors = true
mirrors = http://pypi.iguokr.com/
EOF
cat > ${VENV_DIR}/.pydistutils << "EOF"
[easy_install]
index_url = http://pypi.iguokr.com/guokr/dev/+simple
EOF

${VENV_DIR}/bin/pip install circus==0.11.1 tsuru-circus tsuru-unit-agent
pip install tsuru-unit-agent

sed -ri 's/^session\s+required\s+pam_loginuid.so$/session optional pam_loginuid.so/' /etc/pam.d/sshd
mkdir /var/run/sshd
echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile

mkdir -p /etc/circus
cp ${SOURCE_DIR}/utils/circus.ini /etc/circus/circus.ini

