#!/bin/bash -el

SOURCE_DIR=/var/lib/tsuru
source ${SOURCE_DIR}/config

mkdir -p /home/application
useradd -m ${USER} -s /bin/bash
chown ${USER}:${USER} /home/application
echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers

# do not remove, circus is needed to manage application processes
# and its environment variables
apt-get update
apt-get install python-virtualenv curl git openssh-server python-pip libzmq-dev g++ python-dev wget libyaml-dev -y
virtualenv ${VENV_DIR}
${VENV_DIR}/bin/pip install circus==0.11.1 tsuru-circus==0.8.3 tsuru-unit-agent==0.1.0
pip install tsuru-unit-agent==0.1.0

sed -ri 's/^session\s+required\s+pam_loginuid.so$/session optional pam_loginuid.so/' /etc/pam.d/sshd
mkdir /var/run/sshd
echo "export DEBIAN_FRONTEND=noninteractive" >> /etc/profile

mkdir -p /etc/circus
cp ${SOURCE_DIR}/utils/circus.ini /etc/circus/circus.ini

wget http://nodejs.org/dist/v0.10.32/node-v0.10.32.tar.gz
tar xvf node-v0.10.32.tar.gz
cd node-v0.10.32 && ./configure && make && sudo make install
echo '-----*-------'
npm install -g npm@1.4.28
npm config set registry http://registry.npm.org
